// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rooster.Storing;

namespace Rooster.Storing.Migrations
{
    [DbContext(typeof(RoosterContext))]
    partial class RoosterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Rooster.Domain.Models.Errand", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descr")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime>("ErrandEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ErrandStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("UserEntityId")
                        .HasColumnType("integer");

                    b.HasKey("EntityId");

                    b.HasIndex("UserEntityId");

                    b.ToTable("Errands");

                    b.HasData(
                        new
                        {
                            EntityId = 1,
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ErrandEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ErrandStart = new DateTime(2021, 5, 26, 19, 22, 41, 950, DateTimeKind.Local).AddTicks(9928),
                            Title = "Meeting"
                        });
                });

            modelBuilder.Entity("Rooster.Domain.Models.User", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("EntityId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            EntityId = 1,
                            Email = "johndoe@example.com"
                        });
                });

            modelBuilder.Entity("Rooster.Domain.Models.Errand", b =>
                {
                    b.HasOne("Rooster.Domain.Models.User", "User")
                        .WithMany("schedule")
                        .HasForeignKey("UserEntityId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rooster.Domain.Models.User", b =>
                {
                    b.Navigation("schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
